routes/web.php
<?php

//Route::get('/', function () {
//    return view('welcome');
// });




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/importer', 'CityController@importer')->name('importer');

Route::get('/admin', 'AdminController@index')->name('admin');

Route::resource('cities', 'CityController');

Route::resource('streets', 'StreetController');

Route::resource('sellingobjects', 'SellingObjectsController');

Route::get('/', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $guard_name = 'web';

    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdminController extends Controller
{
  public function index()
  {
      return view('admin.admin');

  }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\Model\City;
use Illuminate\Http\Request;

class CityController extends Controller
{

    public function index()
    {
        $cities = City::where('delete',0)->paginate(200);
        return view('cities.index',['cities' => $cities]);
    }

    public function create()
    {
        return view('cities.create');

    }

    public function store(Request $request)
    {
        $city = new City();
        $city->cityname = $request->citta;
        $city->zipcode = $request->zipcode;
        $city->provincia = $request->provincia;
        $city->regione = $request->regione;
        $city->save();
        return redirect()->route('cities.index');

    }

    public function show($id)
    {


    }


    public function edit($id)
    {
        $city = City::where('id',$id)->first();
        return view('cities.edit',['city' => $city]);

    }

    public function update(Request $request, $id)
    {
        $city = City::where('id',$id)->first();
        $city->cityname = $request->citta;
        $city->zipcode = $request->zipcode;
        $city->provincia = $request->provincia;
        $city->regione = $request->regione;
        $city->save();
        return redirect()->route('cities.index');

    }

    public function destroy($id)
    {
        $city = City::where('id',$id)->first();
        $city->delete = 1;
        $city->save();
        return redirect()->route('cities.index');
    }

    public function importer()
    {

        if (($handle = fopen(public_path() . '/cap.csv', 'r')) !== FALSE) {
            while (($data = fgetcsv($handle, 1000, ';')) !== FALSE) {


                $csv_data = new City();
                $csv_data->cityname = $data [0];
                $csv_data->zipcode = $data [1];
                $csv_data->provincia = $data [2];
                $csv_data->regione = $data [3];
                $csv_data->save();
            }
        }
        fclose($handle);

        $finalData = $csv_data::all();

        return view('importer', [
            "data" => $finalData,
        ]);
    }
 }

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }


}

app/Http/Controllers/SellingObjectsController.php
<?php

namespace App\Http\Controllers;

use App\Model\SellingObjects;
use Illuminate\Http\Request;


class SellingObjectsController extends Controller
{

    public function index()
    {

        $sellingobjects = SellingObjects::where('delete',0)->paginate(50);
        return view('sellingobjects.index',['sellingobjects' => $sellingobjects]);
    }

    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        //
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/StreetController.php
<?php


namespace App\Http\Controllers;
use App\Model\City;
use App\Model\Street;
use Illuminate\Http\Request;

class StreetController extends Controller
{

    public function index()
    {
        $streets = Street::where('delete',0)->paginate(50);
        return view('streets.index',['streets' => $streets]);
    }

    public function create()
    {
        $cities = City::where('delete',0)->get();
        return view('streets.create',['cities' => $cities]);
    }


    public function store(Request $request)
    {

        $streets = new Street();

        $streets->city_id = $request->city;

        $streets->streetname = $request->streetname;

        $streets->streetnumber = $request->streetnumber;

        // dd($request);
        $streets->save();



        return redirect()->route('streets.index');
    }


    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $street = Street::where('id',$id)->first();
        $cities = City::where('delete',0)->get();

        return view('streets.edit',[  'street' => $street,
                                            'cities' => $cities]);
    }

    public function update(Request $request, $id)
    {
        $streets = Street::where('id',$id)->first();
        $streets->city_id = $request->city;
        $streets->streetname = $request->streetname;
        $streets->streetnumber = $request->streetnumber;
        $streets->save();
        return redirect()->route('streets.index');


    }


    public function destroy($id)
    {
        $streets = Street::where('id',$id)->first();
        $streets->delete =1;
        $streets->save();
        return redirect()->route('streets.index');
    }
}

resources/views/admin/admin.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Dashboard Admin</h1>
@stop

@section('content')
    <p>You are logged in! </p>
@stop

resources/views/cities/create.blade.php
@extends('adminlte::page')

@section('title', 'Modifica Città')

@section('content_header')
    <h2 class="my-3">Creazione Città</h2>
@stop

@section('content')


    @if($errors->all())
        <div class="alert alert-danger">
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif

    @if (session()->has('message'))
        <div class="alert alert-success">
            {{session()->get('message')}}
        </div>
    @endif


    <form action="{{route('cities.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="citta">Nome Città</label>
            <input type="text" name="citta" id="citta" class="form-control">
        </div>


        <div class="form-group">
            <label for="zipcode">Codice Postale</label>
            <input type="text" name="zipcode" id="zipcode" class="form-control">
        </div>


        <div class="form-group">
            <label for="provincia">Provincia Città</label>
            <input type="text" name="provincia" id="provincia" class="form-control">
        </div>

        <div class="form-group">
            <label for="regione">Regione</label>
            <input type="text" name="regione" id="regione" class="form-control">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Aggiungi Città</button>
        </div>
    </form>
@endsection

resources/views/cities/edit.blade.php
@extends('adminlte::page')

@section('title', 'Modifica Città')

@section('content_header')
    <h2 class="my-3">Modificare Città</h2>
@stop

@section('content')


    @if($errors->all())
        <div class="alert alert-danger">
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif

    @if (session()->has('message'))
        <div class="alert alert-success">
            {{session()->get('message')}}
        </div>
    @endif

    <form action="{{route('cities.update', $city->id)}}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="citta">Nome Città</label>
            <input type="text" name="citta" id="citta" class="form-control" value='{{$city->cityname}}'>
        </div>


        <div class="form-group">
            <label for="zipcode">Codice Postale</label>
            <input type="text" name="zipcode" id="zipcode" class="form-control" value='{{$city->zipcode}}'>
        </div>


        <div class="form-group">
            <label for="provincia">Provincia Città</label>
            <input type="text" name="provincia" id="provincia" class="form-control" value='{{$city->provincia}}'>
        </div>

        <div class="form-group">
            <label for="regione">Regione</label>
            <input type="text" name="regione" id="regione" class="form-control" value='{{$city->regione}}'>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Aggiorna Città</button>
        </div>
    </form>
@endsection

resources/views/cities/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Lista Città <a href= "{{ route('cities.create') }}" class="btn btn-success btn-lg">Create</a> </h1>
@stop

@section('content')
    <div class="container">
        @foreach($cities as $city)
            <div class="row">
                <div class="col-sm-6">
                    {{$city->cityname}}
                </div>
                <div class="col-sm-6">
                    <form onsubmit="" class="col-md-2 form-inline" method="GET" action="{{ route('cities.edit', $city->id) }}">
                        @csrf
                        @method('get')
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-edit"></span> EDIT
                        </button>
                    </form>

                    <form onsubmit="return confirm('Vuoi Cancellare?')" class="col-md-2 form-inline" method="POST" action="{{ route('cities.destroy', $city->id) }}">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span> DELETE
                        </button>
                    </form>
                </div>
            </div>
        @endforeach
    </div>
    {{$cities->links()}}
@stop

resources/views/home.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>PT-GAME</h1>
@stop

@section('content')
    <p>Sei loggato come admin</p>
@stop

resources/views/importer.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Raleway', sans-serif;
            font-weight: 100;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 12px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>cityname</th>
        <th>zipcode</th>
        <th>provincia</th>
        <th>regione</th>
    </tr>
    </thead>
    <tbody>
    @foreach($data as $item)
        <tr>
            <td>{{$item->id}}</td>
            <td>{{$item->cityname}}</td>
            <td>{{$item->zipcode}}</td>
            <td>{{$item->provincia}}</td>
            <td>{{$item->regione}}</td>
        </tr>
    @endforeach
    </tbody>
</table>




</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/sellingobjects/create.blade.php
@extends('adminlte::page')

@section('title', 'Modifica Oggetto')

@section('content_header')
    <h2 class="my-3">Creazione Oggetto</h2>
@stop

@section('content')


    @if($errors->all())
        <div class="alert alert-danger">
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif

    @if (session()->has('message'))
        <div class="alert alert-success">
            {{session()->get('message')}}
        </div>
    @endif


    <form action="{{route('sellingobjects.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="nameobjects">Nome Oggetto</label>
            <input type="text" name="nameobjects" id="nameobject" class="form-control">
        </div>


        <div class="form-group">
            <label for="numberobject">Numero Oggetto</label>
            <input type="text" name="numberobject" id="numberobject" class="form-control">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Aggiungi Oggetto</button>
        </div>
    </form>
@endsection

resources/views/sellingobjects/edit.blade.php
@extends('adminlte::page')

@section('title', 'Modifica Oggetto')

@section('content_header')
    <h2 class="my-3">Modificare Oggetto</h2>
@stop

@section('content')


    @if($errors->all())
        <div class="alert alert-danger">
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif

    @if (session()->has('message'))
        <div class="alert alert-success">
            {{session()->get('message')}}
        </div>
    @endif

    <form action="{{route('sellingobjects.update', $city->id)}}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="nameobjects">Nome Oggetto</label>
            <input type="text" name="nameobjects" id="nameobjects" class="form-control" value='{{$city->cityname}}'>
        </div>


        <div class="form-group">
            <label for="numberobject">Numero Oggetto/label>
            <input type="text" name="numberobject" id="numberobject" class="form-control" value='{{$city->zipcode}}'>
        </div>


        <div class="form-group">
            <button type="submit" class="btn btn-primary">Aggiorna Città</button>
        </div>
    </form>
@endsection

resources/views/sellingobjects/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Lista Oggetti <a href= "{{ route('sellingobjects.create') }}" class="btn btn-success btn-lg">Create</a> </h1>
@stop

@section('content')
    <div class="container">
        @foreach($sellingobjects as $sellingobject)
            <div class="row">
                <div class="col-sm-6">
                    {{$sellingobjects->objectsname}}
                </div>
                <div class="col-sm-6">
                    <form onsubmit="" class="col-md-2 form-inline" method="GET" action="{{ route('sellingobjects.edit', $sellingobjects->id) }}">
                        @csrf
                        @method('get')
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-edit"></span> EDIT
                        </button>
                    </form>

                    <form onsubmit="return confirm('Vuoi Cancellare?')" class="col-md-2 form-inline" method="POST" action="{{ route('sellingobjects.destroy', $sellingobjects->id) }}">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span> DELETE
                        </button>
                    </form>
                </div>
            </div>
        @endforeach
    </div>
    {{$sellingobjects->links()}}
@stop

resources/views/streets/create.blade.php
@extends('adminlte::page')

@section('title', 'Modifica Città')

@section('content_header')
    <h2 class="my-3">Creazione Via</h2>
@stop

@section('content')


    @if($errors->all())
        <div class="alert alert-danger">
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif

    @if (session()->has('message'))
        <div class="alert alert-success">
            {{session()->get('message')}}
        </div>
    @endif


    <form action="{{route('streets.store')}}" method="post">
        @csrf
         <div class="form-group">
            <label for="city">Select list:</label>
            <select class="form-control" id="city" name="city">
                @foreach($cities as $city)
                <option value="{{$city->id}}">{{$city->cityname}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="streetname">Via o Piazza</label>
            <input type="text" name="streetname" id="streetname" class="form-control">
        </div>

        <div class="form-group">
            <label for="streetnumber">Numero Civico</label>
            <input type="text" name="streetnumber" id="streetnumber" class="form-control">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Aggiungi Via</button>
        </div>
    </form>
@endsection

resources/views/streets/edit.blade.php
@extends('adminlte::page')

@section('title', 'Modifica Città')

@section('content_header')
    <h2 class="my-3">Modificare Città</h2>
@stop

@section('content')


    @if($errors->all())
        <div class="alert alert-danger">
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </div>
    @endif

    @if (session()->has('message'))
        <div class="alert alert-success">
            {{session()->get('message')}}
        </div>
    @endif

    <form action="{{route('streets.update', $street->id)}}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="city">Select list:</label>
            <select class="form-control" id="city" name="city">
                @foreach($cities as $city)
                    <option @if($city->id == $street->city->id) selected="selected" @endif value="{{$city->id}}">{{$city->cityname}}</option>
                @endforeach
            </select>
        </div>


        <div class="form-group">
            <label for="via">Via</label>
            <input type="text" name="streetname" id="via" class="form-control" value='{{$street->streetname}}'>
        </div>


        <div class="form-group">
            <label for="provincia">Provincia Città</label>
            <input type="text" name="streetnumber" id="numerocivico" class="form-control" value='{{$street->streetnumber}}'>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Aggiorna Via</button>
        </div>
    </form>
@endsection

resources/views/streets/index.blade.php
@extends('adminlte::page')

@section('title', 'Lista Strade')

@section('content_header')
    <h1>Lista Strade  <a href= "{{ route('streets.create') }}" class="btn btn-success btn-lg">Create</a> </h1>


@stop

@section('content')
    <div class="container">
        @foreach($streets as $street)
            <div class="row">
                <div class="col-sm-6">
                {{$street->city->cityname}} - {{$street->streetname}}, {{$street->streetnumber}}
                </div>
                <div class="col-sm-6">
                    <form onsubmit="" class="col-md-2 form-inline" method="GET" action="{{ route('streets.edit', $street->id) }}">
                        @csrf
                        @method('get')
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-edit"></span> EDIT
                        </button>
                    </form>

                    <form onsubmit="return confirm('Vuoi Cancellare?')" class="col-md-2 form-inline" method="POST" action="{{ route('streets.destroy', $street->id) }}">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span> DELETE
                        </button>
                    </form>
                </div>
            </div>
        @endforeach
    </div>
@stop